def AWS_REGION  = 'us-east-1'
def AWS_ACCOUNT = '433214487294'
def ECR_REPO    = 'aiops/sample-app'
def VERSION     = '2.1.2'
def IMAGE_URI   = "${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPO}:${VERSION}"

pipeline {
    agent any

    environment {
        PATH = "/opt/apache-maven-3.9.4/bin:$PATH"
    }

    stages {

        stage('Checkout from Git') {
            steps {
                git branch: 'feature',
                    url: 'https://github.com/5K7-BUG/DevOps-Projects.git'
            }
        }

        stage('Build & Package') {
            steps {
                echo "Maven build started"
                sh '''
                  cd DevOps-Project-06
                  mvn clean package
                '''
                echo "Maven build completed"
            }
        }

        stage('SonarQube Analysis') {
            environment {
                scannerHome = tool 'sonarqube-scanner-tool'
            }
            steps {
                withSonarQubeEnv('sonarqube-scanner') {
                    sh '''
                      cd DevOps-Project-06
                      ${scannerHome}/bin/sonar-scanner
                    '''
                }
            }
        }

        /*stage('Quality Gate') {
            steps {
                timeout(time: 1, unit: 'HOURS') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }*/

        stage('Docker Build') {
            steps {
                sh "docker build -t ${ECR_REPO}:${VERSION} DevOps-Project-06/"
            }
        }
        stage('Trivy FS Scan') {
            steps {
                sh '''
                trivy fs \
                  --severity HIGH,CRITICAL \
                  --no-progress \
                  DevOps-Project-06
                '''
            }
        }
        stage('Trivy Image Scan') {
            steps {
                sh '''
                trivy image \
                  --format json \
                  --output trivy-report.json \
                  aiops/sample-app:2.1.2
                '''
            }
        }
        stage('OPA Policy Check') {
            steps {
                script {
                    sh '''
                    result=$(opa eval \
                      --format raw \
                      --data DevOps-Project-06/trivy.rego \
                      --input trivy-report.json \
                      "data.trivy.security.allow")
        
                    if [ "$result" != "true" ]; then
                      echo "OPA policy violation: CRITICAL vulnerabilities present"
                      exit 1
                    fi
                    '''
                }
            }
        }

        stage('ECR Login') {
            steps {
                sh """
                  aws ecr get-login-password --region ${AWS_REGION} \
                  | docker login --username AWS --password-stdin \
                  ${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com
                """
            }
        }

        stage('Docker Tag & Push') {
            steps {
                sh """
                  docker tag ${ECR_REPO}:${VERSION} ${IMAGE_URI}
                  docker push ${IMAGE_URI}
                """
            }
        }
    }

    post {
        success {
            echo "Pipeline SUCCESS"
        }
        failure {
            echo "Pipeline FAILED"
        }
        always {
            cleanWs()
        }
    }
}
